ALTER TABLE Entidades ADD CONSTRAINT UK_ENTIDADES UNIQUE (correo);
ALTER TABLE Medicamentos ADD CONSTRAINT UK_MEDICAMENTOS UNIQUE (nombre);
ALTER TABLE Medicos ADD CONSTRAINT UK_MEDICOS UNIQUE (correo);
ALTER TABLE Pacientes ADD CONSTRAINT UK_PACIENTES_CORREO UNIQUE (correo);