ALTER TABLE HistoriasClinicas DROP CONSTRAINT FK_HistoriasClinicas_Pacientes;

ALTER TABLE HistoriasClinicas ADD CONSTRAINT FK_HistoriasClinicas_Pacientes FOREIGN KEY(paciente_id) REFERENCES Pacientes(id) ON DELETE CASCADE;

ALTER TABLE Pagos DROP CONSTRAINT FK_PAGOS_PACIENTES;

ALTER TABLE Pagos ADD CONSTRAINT FK_PAGOS_PACIENTES FOREIGN KEY (paciente_id) REFERENCES Pacientes(id) ON DELETE CASCADE;
