/*PC_MEDICOS*/
CREATE OR REPLACE PACKAGE PC_MEDICOS IS 
    PROCEDURE AD_MEDICOS(x_nombre IN VARCHAR ,x_apellido IN VARCHAR,x_identificacion IN NUMBER,x_correo IN VARCHAR,x_telefono IN NUMBER,x_estado IN VARCHAR,x_numero_consultorio IN NUMBER);
    PROCEDURE MO_MEDICOS(x_nombre IN VARCHAR ,x_apellido IN VARCHAR,x_identificacion IN NUMBER,x_correo IN VARCHAR,x_telefono IN NUMBER,x_estado IN VARCHAR,x_numero_consultorio IN NUMBER);
    PROCEDURE DEL_MEDICOS(x_identificacion IN NUMBER);
    FUNCTION CO_ESPECIALISTAS RETURN SYS_REFCURSOR;
END PC_MEDICOS;
/
/*PC_HISTORIAS_CLINICAS*/
CREATE OR REPLACE PACKAGE PC_HISTORIAS_CLINICAS IS
    PROCEDURE AD_HISTORIAS_CLINICAS(x_historia_id IN NUMBER, x_paciente_id IN NUMBER,x_nombre_entidad IN VARCHAR,x_fechaConsulta IN DATE, x_motivoConsulta IN VARCHAR, x_diagnostico IN VARCHAR, x_tratamiento IN VARCHAR, x_fecha IN DATE);
    PROCEDURE MO_HISTORIAS_CLINICAS(x_historia_id IN NUMBER, x_paciente_id IN NUMBER,x_nombre_entidad IN VARCHAR,x_fechaConsulta IN DATE, x_motivoConsulta IN VARCHAR, x_diagnostico IN VARCHAR, x_tratamiento IN VARCHAR, x_fecha IN DATE);
    PROCEDURE DEL_HISTORIAS_CLINICAS(x_historia_id IN NUMBER);
END PC_HISTORIAS_CLINICAS;
/
/*PC_MEDICAMENTOS*/
CREATE OR REPLACE PACKAGE PC_MEDICAMENTOS IS
    PROCEDURE AD_MEDICAMENTOS(x_nombre IN VARCHAR, x_id IN NUMBER, x_unidades IN NUMBER);
    FUNCTION CO_MEDICAMENTOS RETURN SYS_REFCURSOR;
    FUNCTION CO_MEDICAMENTO_HOSPITAL RETURN SYS_REFCURSOR;
END PC_MEDICAMENTOS;
/
/*PC_PACIENTES*/
CREATE OR REPLACE PACKAGE PC_PACIENTES IS 
    PROCEDURE AD_PACIENTES(x_nombre IN VARCHAR,x_apellido IN VARCHAR,x_id IN NUMBER,x_correo IN VARCHAR,x_metodosDePago IN VARCHAR,x_residencia IN VARCHAR);
    PROCEDURE MO_PACIENTES(x_id IN NUMBER, x_metodosDePago IN VARCHAR,x_residencia IN VARCHAR);
    PROCEDURE DEL_PACIENTES(x_id IN NUMBER);
    FUNCTION CO_PACIENTES_CITAS RETURN SYS_REFCURSOR;
    FUNCTION CO_PACIENTES_TIENE_PACIENTES RETURN SYS_REFCURSOR;
    FUNCTION CO_PACIENTES_CITA_FECHA RETURN SYS_REFCURSOR;
    FUNCTION CO_PACIENTES_PAGO RETURN SYS_REFCURSOR;
END PC_PACIENTES;
/
/*PC_CITAS*/
CREATE OR REPLACE PACKAGE PC_CITAS IS
    PROCEDURE AD_CITAS(x_cita_id IN NUMBER,x_paciente_id IN NUMBER, x_fechaHora IN DATE,x_motivo IN VARCHAR,x_estado IN VARCHAR,x_observaciones IN VARCHAR,x_identificacion IN NUMBER, x_pago_id IN NUMBER);
    FUNCTION CO_CITAS RETURN SYS_REFCURSOR;
END PC_CITAS;
/