CREATE ROLE Secretario;
CREATE ROLE Gerente_Hospital;
CREATE ROLE Medico_1;
GRANT EXECUTE ON PA_GERENTE TO Gerente_Hospital;
GRANT EXECUTE ON PA_ADMINISTRATIVOS TO Secretario;
GRANT EXECUTE ON PA_MEDICO TO Medico_1;