DROP TRIGGER TG_CONSULTORIO;
DROP TRIGGER TG_MODIFICAR_MEDICOS;
DROP TRIGGER TG_Medicamentos;
DROP TRIGGER TG_HISTORIAS_CLINICAS_MODIFICAR;
DROP TRIGGER TG_HISTORIAS_CLINICAS_ELIMINAR;
DROP TRIGGER TG_TIPOS_CITAS;
DROP TRIGGER TG_ASISTENCIA_CITA;
DROP TRIGGER TG_PACIENTES_MODIFICAR;