ALTER TABLE PacientePideMedicamentos ADD CONSTRAINT FK_PIDEMEDICAMENTOS_PACIENTE FOREIGN KEY (id_Paciente) REFERENCES Pacientes(id);
ALTER TABLE PacientePideMedicamentos ADD CONSTRAINT FK_PIDEMEDICAMENTOS_MEDICAMENTOS FOREIGN KEY(id_Medicamentos) REFERENCES Medicamentos(id);
ALTER TABLE DiagnosticoAsignaMedicamentos ADD CONSTRAINT FK_ASIGNA_MEDICAMENTOS_MEDICAMENTOS FOREIGN KEY(id_medicamentos) REFERENCES Medicamentos(id);
ALTER TABLE DiagnosticoAsignaMedicamentos ADD CONSTRAINT FK_ASIGNA_MEDICAMENTOS_DIAGNOSTICOS FOREIGN KEY (diagnostico_id) REFERENCES Diagnosticos(diagnostico_id);
ALTER TABLE MGeneral ADD CONSTRAINT FK_MGENERAL_MEDICOS FOREIGN KEY(identificacion_m_general) REFERENCES Medicos(identificacion);
ALTER TABLE Especialistas ADD CONSTRAINT FK_ESPECIALISTAS_MEDICOS FOREIGN KEY(identificacion_especialistas) REFERENCES Medicos(identificacion);
ALTER TABLE MedicosGeneraDiagnosticos ADD CONSTRAINT FK_MEDICOSGENERANDIAGNOSTICO_DIAGNOSTICOS FOREIGN KEY(diagnostico_id) REFERENCES Diagnosticos(diagnostico_id);
ALTER TABLE MedicosGeneraDiagnosticos ADD CONSTRAINT FK_MEDICOSGENERANDIAGNOSTICO_MEDICOS FOREIGN KEY(identificacion_medico) REFERENCES Medicos(identificacion);
ALTER TABLE PacientePidePruebasLaboratorio ADD CONSTRAINT FK_PACIENTEPIDE_PACIENTES FOREIGN KEY(id_paciente) REFERENCES Pacientes(id);
ALTER TABLE PacientePidePruebasLaboratorio ADD CONSTRAINT FK_PACIENTEPIDE_LABORATORIO FOREIGN KEY(id_prueba_laboratorio) REFERENCES PruebaDeLaboratorio(id_prueba);
ALTER TABLE JefeLaboratorioOrganizaJornadasDeVacunacion ADD CONSTRAINT FK_JEFE_VACU_JEFE FOREIGN KEY(id_jefe) REFERENCES JefesLaboratorio(id_jefe);
ALTER TABLE JefeLaboratorioOrganizaJornadasDeVacunacion ADD CONSTRAINT FK_JEFE_VACU_JORNADA FOREIGN KEY(id_jornada) REFERENCES JornadasDeVacunacion(id_jornada);
ALTER TABLE PruebasLaboratorioJefeLaboratorio ADD CONSTRAINT FK_PRUEBA_LABORATORIO_PRUEBA FOREIGN KEY(id_prueba) REFERENCES PruebaDeLaboratorio(id_prueba);
ALTER TABLE PruebasLaboratorioJefeLaboratorio ADD CONSTRAINT FK_PRUEBA_LABORATORIO_JEFE FOREIGN KEY(id_jefe) REFERENCES JefesLaboratorio(id_jefe);
ALTER TABLE MedioComunicacionEnviaNotificacion ADD CONSTRAINT FK_MEDIOENVIA_NOTIFICACION FOREIGN KEY(id_notificacion) REFERENCES Notificaciones(id_notificacion);
ALTER TABLE MedioComunicacionEnviaNotificacion ADD CONSTRAINT FK_MEDIOENVIA_MEDIO FOREIGN KEY(id_medio) REFERENCES MediosDeComunicacion(id_medio);
ALTER TABLE LaboratoriosGeneranMedicamentos ADD CONSTRAINT FK_LABORATORIOS_GENERAN_MEDICAMENTOS_LAB FOREIGN KEY(id_laboratorio) REFERENCES Laboratorios(id_laboratorio);
ALTER TABLE LaboratoriosGeneranMedicamentos ADD CONSTRAINT FK_LABORATORIOS_GENERAN_MEDICAMENTOS_MEDICA FOREIGN KEY(id_medicamentos) REFERENCES Medicamentos(id);
ALTER TABLE Laboratorios ADD CONSTRAINT FK_LABORATORIOS_JEFE FOREIGN KEY(id_jefe) REFERENCES JefesLaboratorio(id_jefe);
ALTER TABLE LaboratoriosTienenJefesLaboratorios ADD CONSTRAINT FK_TIENEN_LABORATORIO FOREIGN KEY(id_laboratorio) REFERENCES Laboratorios(id_laboratorio);
ALTER TABLE LaboratoriosTienenJefesLaboratorios ADD CONSTRAINT FK_LABORATORIOS_TIENEN_JEFES_LABORATORIO_JEFE FOREIGN KEY(id_jefe) REFERENCES JefesLaboratorio(id_jefe);
ALTER TABLE MediosDeComunicacion ADD CONSTRAINT FK_MEDIOS_DE_COMUNICACION_JEFE FOREIGN KEY(id_jefe) REFERENCES JefesLaboratorio(id_jefe);
ALTER TABLE JefesLaboratoriosRegistraResultadoPruebas ADD CONSTRAINT FK_JEFES_RESULTADO_PRUEBAS FOREIGN KEY(id_resultado) REFERENCES ResultadoPruebas(id_resultado);
ALTER TABLE JefesLaboratoriosRegistraResultadoPruebas ADD CONSTRAINT FK_JEFES_RESULTADOPRUEBAS_JEFES FOREIGN KEY(id_jefe) REFERENCES JefesLaboratorio(id_jefe);
ALTER TABLE MedicosResultadoPruebas ADD CONSTRAINT FK_MEDICOSRESULTADOS_RESULTADOS FOREIGN KEY(id_resultado) REFERENCES ResultadoPruebas(id_resultado);
ALTER TABLE MedicosResultadoPruebas ADD CONSTRAINT FK_MEDICOSRESULTADOS_IDENTIFICACION FOREIGN KEY(identificacion) REFERENCES Medicos (identificacion);
ALTER TABLE PruebaDeLaboratorio ADD CONSTRAINT FK_PRUEBA_DIAGNOSTICO FOREIGN KEY(id_diagnostico) REFERENCES Diagnosticos(diagnostico_id);
ALTER TABLE Observaciones ADD CONSTRAINT FK_OBSERVACIONES_RESULTADOS FOREIGN KEY (id_resultado) REFERENCES ResultadoPruebas(id_resultado);
ALTER TABLE RecepcionNotificacion ADD CONSTRAINT FK_RECEPCION_NOTIFICACION FOREIGN KEY(id_notificacion_recepcion) REFERENCES Notificaciones(id_notificacion);
ALTER TABLE Notificaciones ADD CONSTRAINT FK_NOTIFICACIONES_JORNADAS_DE_VACUNACION FOREIGN KEY(id_jornada_notificaciones) REFERENCES JornadasDeVacunacion(id_jornada);
ALTER TABLE Notificaciones ADD CONSTRAINT FK_NOTIFICACIONES_IDENTIFICACION_MEDICOS FOREIGN KEY(identificacion_medicos) REFERENCES Medicos(identificacion);
ALTER TABLE Notificaciones ADD CONSTRAINT FK_NOTIFICACIONES_RESULTADOS FOREIGN KEY(id_resultado) REFERENCES ResultadoPruebas(id_resultado);
ALTER TABLE Notificaciones ADD CONSTRAINT FK_NOTIFICACIONES_JEFE_LAB FOREIGN KEY(id_jefe) REFERENCES JefesLaboratorio(id_jefe);
ALTER TABLE Notificaciones ADD CONSTRAINT FK_NOTIFICACIONES_PACIENTES FOREIGN KEY(id_paciente) REFERENCES Pacientes(id);
ALTER TABLE MedicosAsignanPruebas ADD CONSTRAINT FK_MEDICOS_ASIGNAN_PRUEBAS FOREIGN KEY(id_pruebas) REFERENCES PruebaDeLaboratorio(id_prueba);
ALTER TABLE MedicosAsignanPruebas ADD CONSTRAINT FK_MEDICOS_ASIGNAN_PRUEBAS_MEDICOS FOREIGN KEY(identificacion_medicos) REFERENCES Medicos(identificacion);
ALTER TABLE JefeDeLaboratorioRealizaPruebaDeLaboratorio ADD CONSTRAINT FK_JEFE_REALIZA_PRUEBAS FOREIGN KEY(id_prueba) REFERENCES PruebaDeLaboratorio(id_prueba);
ALTER TABLE JefeDeLaboratorioRealizaPruebaDeLaboratorio ADD CONSTRAINT FK_JEFE_REALIZA_JEFE FOREIGN KEY(id_jefe) REFERENCES JefesLaboratorio(id_jefe);