DROP PACKAGE PC_JEFE_LABORATORIO;
DROP PACKAGE PC_LABORATORIOS;
DROP PACKAGE PC_JORNADAS_DE_VACUNACION;
DROP PACKAGE PC_PRUEBAS_DE_LABORATORIO;
DROP PACKAGE PC_RESULTADO_PRUEBAS;
DROP PACKAGE PC_NOTIFICACIONES;