--PC_JEFE_LABORATORIO
CREATE OR REPLACE PACKAGE PC_JEFE_LABORATORIO IS  
    PROCEDURE AD_JEFE(x_id_jefe IN NUMBER, x_nombre IN VARCHAR, x_apellido IN VARCHAR, x_telefono NUMBER, x_correoElectronico IN VARCHAR, x_estado IN VARCHAR);
    PROCEDURE MO_JEFE(x_id_jefe IN NUMBER,x_telefono IN NUMBER);
    PROCEDURE DEL_JEFE(x_id_jefe IN NUMBER);
    FUNCTION CO_JEFELAB RETURN SYS_REFCURSOR;
END PC_JEFE_LABORATORIO;
/
--PC_LABORATORIOS
CREATE OR REPLACE PACKAGE PC_LABORATORIOS IS
    PROCEDURE AD_LAB(x_id_laboratorio IN NUMBER,x_nombre IN VARCHAR,x_direccion IN VARCHAR,x_contacto IN NUMBER, x_id_jefe IN NUMBER);
    PROCEDURE MO_LAB(x_id_laboratorio IN NUMBER,x_direccion  IN VARCHAR,x_contacto IN NUMBER);
    PROCEDURE DEL_LAB(x_id_laboratorio IN NUMBER);
    FUNCTION CO_LAB RETURN SYS_REFCURSOR;
END PC_LABORATORIOS;
/
--PC_JORNADAS_DE_VACUNACION
CREATE OR REPLACE PACKAGE PC_JORNADAS_DE_VACUNACION IS
    PROCEDURE AD_JORNADAS(x_id_jornada IN NUMBER,x_fecha IN DATE,x_lugar IN VARCHAR,x_tipoDeVacuna IN VARCHAR,x_cantidadVacunasDisponibles IN NUMBER);
    PROCEDURE MO_JORNADAS(x_id_jornada IN NUMBER,x_tipoDeVacuna IN VARCHAR);
    PROCEDURE DEL_JORNADAS(x_id_jornada IN NUMBER);
    FUNCTION CO_JORNADAS RETURN SYS_REFCURSOR;
END PC_JORNADAS_DE_VACUNACION;
/
--PC_PRUEBAS_DE_LABORATORIO
CREATE OR REPLACE PACKAGE PC_PRUEBAS_DE_LABORATORIO IS
    PROCEDURE AD_PRUEBAS(x_id_prueba IN NUMBER,x_tipoDePrueba IN VARCHAR,x_fecha_realizacion IN DATE,x_resultadoPrevio IN VARCHAR,x_estado IN VARCHAR,x_id_diagnostico IN NUMBER);
    PROCEDURE MO_PRUEBAS(x_id_prueba IN NUMBER,x_estado IN VARCHAR);
    PROCEDURE DEL_PRUEBAS(x_id_prueba IN NUMBER);
    FUNCTION CO_PRUEBAS RETURN SYS_REFCURSOR;
END PC_PRUEBAS_DE_LABORATORIO;
/
--PC_RESULTADO_PRUEBAS
CREATE OR REPLACE PACKAGE PC_RESULTADO_PRUEBAS IS
    PROCEDURE AD_RESULTADOS(x_id_resultados IN NUMBER,x_resultado IN VARCHAR,x_fechaRegistro IN DATE);
    FUNCTION CO_RESULTADOS RETURN SYS_REFCURSOR;
END PC_RESULTADO_PRUEBAS;
/
--PC_NOTIFICACIONES
CREATE OR REPLACE PACKAGE PC_NOTIFICACIONES IS
    PROCEDURE AD_NOTI(x_id_notificacion IN NUMBER,x_contenido IN XMLTYPE, x_id_jornada_notificaciones IN NUMBER, x_identificacion_medicos IN NUMBER, x_id_resultado IN NUMBER, x_id_jefe IN NUMBER, x_id_paciente IN NUMBER);
    FUNCTION CO_NOTI RETURN SYS_REFCURSOR;
END PC_NOTIFICACIONES;
/