---Roles---
DROP ROLE Gerente_Laboratorio;
DROP ROLE Jefe_Laboratorio;
DROP ROLE Junta;
DROP ROLE Secretario;

---ActoresE---
DROP PACKAGE PA_GERENTE_LABORATORIO;
DROP PACKAGE PA_JEFE_LABORATORIO;
DROP PACKAGE PA_JUNTA_ADMINISTRATIVA;
DROP PACKAGE PA_SECRETARIO;